body:
  - type: textarea
    id: background
    attributes:
      label: Background
      description: "Please provide a background for the creation of this proposal."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: "What is the proposal of this discussion?"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: "Why should this proposal be implemented?"
  - type: checkboxes
    id: stage
    attributes:
      label: Stage
      description: "The stage of this proposal. Indicates how close it is to being implemented."
      options:
        - label: Draft
          required: true
        - label: Proposal
        - label: Ready
        - label: In Progress
        - label: Implemented
