name: Issue Triage
on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  issue-triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/issue-labeler.yml
          not-before: 2025-08-25T20:09:39.587Z
          enable-versioned-regex: 0
