name: Automatic Label Sync
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  labelsync:
    uses: Jaronline/.github/.github/workflows/reusable-labelsync.yml@main
    with:
      repository: Jaronline/Blocksmith